supportLabel: support
supportComment: >
  We use the issue tracker exclusively for bug reports and feature requests.
  However, this issue appears to be a support request.
  Please join our Discord at https://discordsrv.com/discord and go to the #support channel for help with installing or configuring DiscordSRV.
close: true
lock: false
