title: "[MC -> DC] "
labels: ["waiting for support"]
body:
- type: markdown
  attributes:
    value: |
      __Please create a debug report__

      1. Run `/discordsrv debugger start minecraft_to_discord` to enable the debugger
      2. Send messages in Minecraft
      3. Run `/discordsrv debugger upload` command in-game or through console
      4. Paste the link you're given into the field below
- type: input
  id: bin
  attributes:
    label: Your bin.scarsz.me link from the debugger command
    placeholder: "https://bin.scarsz.me/<UUID>#<KEY>"
  validations:
    required: true
