name: DiscordSRV
version: ${version}
description: The most powerful, configurable, open-source Discord bridge plugin out there.
author: Scarsz
authors: [Androkai, Vankka]
website: https://github.com/DiscordSRV/DiscordSRV
api-version: 1.13

main: github.scarsz.discordsrv.DiscordSRV
database: false
loadbefore: [
  StaffPlus # Log4j conflicts with older versions
]
softdepend: [
  # Chat plugins
  Chatty, FancyChat, Herochat, Legendchat, LunaChat, TownyChat, VentureChat,
  # Vanish plugins
  Essentials, PhantomAdmin, SuperVanish,
  # Misc. plugins
  Multiverse-Core, Vault, PlaceholderAPI, mcMMO, LuckPerms, dynmap, Skript
]

commands:
  discord:
    aliases: [discordsrv]
    description: Команди DiscordSRV
    usage: |
           /discord - Показати посилання для запрошення на сервер Discord
           /discord help/? - Показати список команд
           /discord link - Пов'яжіть обліковий запис Minecraft з обліковим записом Discord
           /discord unlink - Видаліть посилання між обліковим записом Minecraft та Discord
           /discord linked - Показувати інформацію про статус прив'язки
           /discord broadcast - Передайте повідомлення на Discord
           /discord debug - Sзавершіть інформацію про налагодження до суті
           /discord reload - Перезавантажте плагін
           /discord resync - Повторна синхронізація всіх груп і ролей
           /discord language - Змінює мову DiscordSRV на будь-яку вказану
           /discord debugger - Перемикається команда, подібна таймінгу, для скидання налагоджувальної інформації в bin.scarsz.me
    permission: discordsrv.discord

permissions:
  discordsrv.player:
    description: батьківська роздільна здатність функцій Discord SRV, пов'язаних з гравцями
    default: true
    children:
      discordsrv.chat: true
      discordsrv.help: true
      discordsrv.link: true
      discordsrv.linked: true
      discordsrv.discord: true
      discordsrv.nicknamesync: true
  discordsrv.admin:
    description: батьківський дозвіл функцій Discord SRV, пов'язаних з адмініструванням
    default: op
    children:
      discordsrv.player: true
      discordsrv.updatenotification: true
      discordsrv.bcast: true
      discordsrv.reload: true
      discordsrv.debug: true
      discordsrv.link.others: true
      discordsrv.linked.others: true
      discordsrv.unlink: true
      discordsrv.unlink.others: true
      discordsrv.resync: true
      discordsrv.groupsyncwithcommands: true
      discordsrv.language: true
  discordsrv.discord:
    description: дозволяє доступ до команди discord
    default: true
  discordsrv.chat:
    description: чи може Користувач перенаправити свій чат на Discord
    default: true
  discordsrv.silentjoin:
    description: чи слід вимикати повідомлення про приєднання для гравців із цим дозволом
    default: false
  discordsrv.silentquit:
    description: чи слід вимикати повідомлення про вихід для гравців із цим дозволом
    default: false
  discordsrv.help:
    description: чи може програвач відображати командну довідку для DiscordSRV
    default: true
  discordsrv.nicknamesync:
    description: чи повинен гравець синхронізувати свій псевдонім із Discord, якщо це дозволено в synchronization.yml
    default: true
  discordsrv.updatenotification:
    description: чи слід повідомляти гравцеві про наявність оновлення в DiscordSRV під час приєднання
    default: op
  discordsrv.bcast:
    description: чи може програвач передавати повідомлення на основний текстовий канал DiscordSRV
    default: op
  discordsrv.reload:
    description: чи може програвач перезавантажити конфігурацію DiscordSRV
    default: op
  discordsrv.debug:
    description: чи може програвач запустити звіт про налагодження
    default: op
  discordsrv.link:
    description: чи може гравець пов'язати свій обліковий запис Minecraft зі своїм обліковим записом Discord
    default: true
  discordsrv.link.others:
    description: чи може гравець прив'язувати акаунти Minecraft інших користувачів до акаунтів Discord
    default: op
  discordsrv.unlink:
    description: чи може гравець відключити свій обліковий запис Minecraft від свого облікового запису Discord
    default: op
  discordsrv.unlink.others:
    description: чи може гравець відключити прив'язку до акаунтів інших людей
    default: op
  discordsrv.linked:
    description: чи може гравець перевірити, з яким обліковим записом Discord пов'язаний його обліковий запис Minecraft
    default: true
  discordsrv.linked.others:
    description: чи може гравець перевірити, до якого облікового запису Discord пов'язані інші облікові записи Minecraft
    default: op
  discordsrv.groupsyncwithcommands:
    description: чи може програвач запустити команду плагіна дозволів, щоб змусити групову синхронізацію
    default: op
  discordsrv.resync:
    description: чи може програвач запустити / discord resync, щоб змусити повторно синхронізувати всі групи / ролі
    default: op
  discordsrv.language:
    description: чи може програвач запустити / discord language, щоб змінити мову плагіна
    default: op
