name: DiscordSRV
version: ${project.version}
description: The most powerful, configurable, open-source Discord bridge plugin out there.
author: Scarsz
authors: [Androkai]
website: https://github.com/DiscordSRV/DiscordSRV
api-version: 1.13

main: github.scarsz.discordsrv.DiscordSRV
database: false
loadbefore: [
  StaffPlus # Log4j conflicts with older versions
]
softdepend: [
  # Permissions plugins
  GroupManager, GroupManagerX, LuckPerms, PermissionsEx, zPermissions,
  # Chat plugins
  HeroChat, Legendchat, LunaChat, TownyChat, UltimateChat, VentureChat,
  # Misc. plugins
  Multiverse-Core, Vault, PlaceholderAPI
]

commands:
  discord:
    aliases: [discordsrv]
    description: DiscordSRV commands
    usage: |
           /discord - Show the invite link of the Discord server
           /discord help/? - Show command list
           /discord link - Link Minecraft account with Discord account
           /discord unlink - Remove link between Minecraft and Discord account
           /discord linked - Show information about linking status
           /discord broadcast - Broadcast a message to Discord
           /discord setpicture - Set the avatar of the bot
           /discord debug - Send debug information to Gist
           /discord reload - Reload the plugin

permissions:
  discordsrv.player:
    description: parent permission of player-related functions of DiscordSRV
    default: true
    children:
      discordsrv.chat: true
      discordsrv.help: true
      discordsrv.link: true
      discordsrv.linked: true
  discordsrv.admin:
    description: parent permission of admin-related functions of DiscordSRV
    default: op
    children:
      discordsrv.player: true
      discordsrv.updatenotification: true
      discordsrv.bcast: true
      discordsrv.setpicture: true
      discordsrv.reload: true
      discordsrv.debug: true
      discordsrv.linked.others: true
      discordsrv.unlink: true
      discordsrv.unlink.others: true
  discordsrv.chat:
    description: whether or not the user is able to have their chat forwarded to Discord
    default: true
  discordsrv.silentjoin:
    description: whether or not to have join messages for players with this permission to be silenced
    default: false
  discordsrv.silentquit:
    description: whether or not to have quit messages for players with this permission to be silenced
    default: false
  discordsrv.help:
    description: whether or not the player is able to display command help for DiscordSRV
    default: true
  discordsrv.updatenotification:
    description: whether or not the player should be told if there's an update to DiscordSRV when joining
    default: op
  discordsrv.bcast:
    description: whether or not the player is able to broadcast messages to the main text channel of DiscordSRV
    default: op
  discordsrv.setpicture:
    description: whether or not the player is able to set the bot's avatar picture
    default: op
  discordsrv.reload:
    description: whether or not the player is able to reload DiscordSRV's configuration
    default: op
  discordsrv.debug:
    description: whether or not the player is able to run a debug report
    default: op
  discordsrv.link:
    description: whether or not the player is able to link their Minecraft account to their Discord account
    default: true
  discordsrv.unlink:
    description: whether or not the player is able to unlink their Minecraft account from their Discord account
    default: op
  discordsrv.unlink.others:
    description: whether or not the player is able to unlink other people's accounts
    default: op
  discordsrv.linked:
    description: whether or not the player is able to check what Discord account their Minecraft account is linked to
    default: true
  discordsrv.linked.others:
    description: whether or not the player is able to check what Discord account other Minecraft accounts are linked to
    default: op