name: Check that PRs are set to develop

on:
  pull_request_target:
   types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: master
          exclude: develop # Don't prevent going from develop -> master
          change-to: develop
          comment: |
            Your PR was set to `master` but as our [Contributing Guidelines](https://github.com/DiscordSRV/DiscordSRV/blob/master/CONTRIBUTING.md) state, PRs should be sent to `develop`
            The base branch of this PR has been automatically changed to `develop`, please check that there are no merge conflicts.
